spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Ecommerce
    username: postgres
    password: ${DB_PASSWORD:456784}
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: ZGV2LW9ubHkta2V5LWRvLW5vdC11c2UtaW4tcHJvZHVjdGlvbi0xMjM0NTY3ODkw
    expiration-ms: 3600000

  seed-data: true

logging:
  level:
    com.project.ecommercebackend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoint:
    health:
      show-details: always
