spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:1800000}

  seed-data: false

logging:
  level:
    root: WARN
    com.project.ecommercebackend: INFO
    org.springframework.security: WARN

server:
  error:
    include-message: never
    include-stacktrace: never

management:
  endpoint:
    health:
      show-details: when-authorized
